[project]
name = "pocketgroups"
version = "0.1.0" # Not used!
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.7",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
classifiers = ["Private :: Do Not Upload"]
